version: "3"
services:
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - /c/Users/bailey/projects/spring-boot-bootstrapper/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=myapp
